### PR TITLE
translation update - pt-BR (100% translated)

### PR DESCRIPTION
**Pull request by leedigital**
@CosmoMyzrailGorynych 
update of the documentation translation into Brazilian Portuguese...

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
There is something wrong with the images. See the logs of Netlify
In any way I'm hyped for the full release, this is a magnificent amount of work 🥳

**Comment by leedigital** [comment]
> There is something wrong with the images. See the logs of Netlify In any way I'm hyped for the full release, this is a magnificent amount of work partying_face

I saw, is that this error is from the files that I'm still going to translate. As I get translated... I'll to fix it. ^_^ 
please wait 15 days for me to finish the full translation. ;-)

**Comment by leedigital** [comment]
ping @CosmoMyzrailGorynych 

translation of the docs to pt-br... 100% translated.

**Comment by CosmoMyzrailGorynych** [comment]
@leedigital Is it ready to be merged? I still see a "wip" in the PR title

**Comment by leedigital** [comment]
> @leedigital Is it ready to be merged? I still see a "wip" in the PR title

Yes... It's just that I needed to review some files. If it is necessary to review other files, make a new PR.

**Pull request merged**
