### PR TITLE
tutorial italian translation

### PR DESCRIPTION
**Pull request by omartek**
Italian translation:
* shooter
* jetty cat
* polishing jetty cat

Some modifications to english version.

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
This PR does not add new navigation entries to
https://github.com/ct-js/docs.ctjs.rocks/blob/master/docs/.vuepress/config.js
so your pages will be inaccessible by regular means

**Comment by CosmoMyzrailGorynych** [comment]
Also please don't make PRs with multiple completely independent changes inside. I can't merge changes to English docs because Italian translation requires changes to navigation.

**Comment by omartek** [comment]
I would have to... I've done three New PR ma they're gone inside one only. I'm not so good with Git, sorry.
How can i make it? Fork again, make a new branch o what else. thx
I will update config.js soon.

**Comment by CosmoMyzrailGorynych** [comment]
I would switch branch to v2.1.0 again, make a new branch there, and cherrypick changes from your branch to the new one.

You can use GitKraken / Github Desktop apps or GitGraph extension for VSCode to simplify things with git. They visualize things well, and merging/cherrypicking/whatever is easier when you can just right-click a needed commit.

**Comment by omartek** [comment]
Thanks for the tips. In this period I've to use GitHub web version, cause using someone else's computer. At point 4 [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository) what is the branch source? Upstream repo or my fork repo?
thank you much

**Comment by omartek** [comment]
I close this pull request and i do it again in the right way.

**Comment by CosmoMyzrailGorynych** [comment]
Using Github web definitely sucks :c

**Pull request closed without merging**
