### PR TITLE
:zap: sidebar: it update for added tutorial

### PR DESCRIPTION
**Pull request by omartek**
Added link to in italian sidebar to deployment-itch-io.md file

I was wondering...
This tutorial is present in Portugues section only. What about adding in english versions? And adding prefix tut- to file name?
Better adding this questions in an issue?

thk

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
> I was wondering...

what do you mean it is not in the english version o_o

**Comment by CosmoMyzrailGorynych** [comment]
It seems that they were lost some day due to a merge conflict. I added them back.

> What about [...] adding prefix tut- to file name? 

They are placed in the "Working with the editor" section, and thus are not tutorials

**Comment by CosmoMyzrailGorynych** [comment]
Also, you should post updates to sidebar and new pages together — they are strict dependencies, after all.

**Comment by omartek** [comment]
Ok. It's all right.

**Pull request closed without merging**
